version: "3"

tasks:
  swagger:
    desc: Generate swagger documentation
    cmds:
      - swag init -g cmd/server/main.go -o cmd/swag/docs

  run:
    desc: Run the server with auto-swagger update
    deps: [swagger]
    cmds:
      - go run cmd/server/main.go

  dev:
    desc: Run the server with auto-swagger update
    deps: [swagger]
    cmds:
      - go run cmd/server/main.go

  build:
    desc: Build the server with auto-swagger update
    deps: [swagger]
    cmds:
      - go build -o ai-bridges cmd/server/main.go
